version: "3"
services:
  nginx:
    restart: always
    image: nguyenquangtungnui/multi-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - client
  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
  redis:
    restart: always
    image: redis:latest
  api:
    restart: always
    image: nguyenquangtungnui/multi-api
    mem_limit: 128m
    hostname: api
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - postgres
      - redis
  worker:
    restart: always
    image: nguyenquangtungnui/multi-worker
    mem_limit: 128m
    hostname: worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  client:
    restart: always
    image: nguyenquangtungnui/multi-client
    mem_limit: 128m
    hostname: client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0
