name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t nguyenquangtungnui/multi-client ./client
      - run: docker build -t nguyenquangtungnui/multi-nginx ./nginx
      - run: docker build -t nguyenquangtungnui/multi-api ./api
      - run: docker build -t nguyenquangtungnui/multi-worker ./worker

      - run: docker push nguyenquangtungnui/multi-client
      - run: docker push nguyenquangtungnui/multi-nginx
      - run: docker push nguyenquangtungnui/multi-api
      - run: docker push nguyenquangtungnui/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-eu-central-1-3031862102600260
          region: eu-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
